---
layout: post
title: 'Overriding the configuration of a Quarkus app from its test code'
date: 2024-06-22
tags: config test development-tips
synopsis: TODO
author: gwenneg
---
:imagesdir: /assets/images/posts/overriding-configuration-from-test-code

Overriding the configuration of a Quarkus app from its test code is often required to achieve a good test coverage.
Whenever a config property determines how the app behaves, all possible config values need to be tested.

[source, java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class MyService {

    @ConfigProperty(name = "new-feature-enabled", defaultValue = "false")
    boolean newFeatureEnabled;

    public void doSomething() {
        if (newFeatureEnabled) {
            // This branch needs to be tested.
        } else {
            // So does that branch.
        }
    }
}
----

There are many ways to override the configuration from the test code.
This post will show you several approaches, with a particular focus on the benefits and drawbacks of each of them.

[NOTE]
====
All code snippets from this post (and more!) are available as code in the https://github.com/gwenneg/blog-overriding-config-properties-from-test-code[gwenneg/blog-overriding-config-properties-from-test-code] repository.
====

== Approach #1: Quarkus test profiles

https://quarkus.io/guides/getting-started-testing#testing_different_profiles[Quarkus test profiles] are one of the best ways to override the configuration.
They can be used while testing in native mode, unlike most approaches listed in this post.
In addition to the config override, they provide https://quarkus.io/guides/getting-started-testing#writing-a-profile[many additional capabilities].

Test profiles suffer however from a few drawbacks.
First, Quarkus is restarted before each test profile is used, which obviously slows down the tests execution.
The tests also have to be split into several test profiles and classes to cover multiple values of the same config properties.
As a result, bigger projects may end up with lots of test profiles and spend a lot of time restarting Quarkus between tests.
Maintaining or reviewing the test code may also be more challenging with test profiles.

Let's take a look at one way to use test profiles.

[source, java, title=The code to be tested]
----
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/features")
public class FeaturesResource {

    @ConfigProperty(name = "awesome-feature-enabled", defaultValue = "false")
    boolean awesomeFeatureEnabled;

    @GET
    @Path("/awesome")
    public boolean isAwesomeFeatureEnabled() {
        return awesomeFeatureEnabled;
    }
}
----

[source, java, title=The test class which is also a test profile]
----
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.junit.QuarkusTestProfile;
import io.quarkus.test.junit.TestProfile;
import io.restassured.RestAssured;
import java.util.Map;
import org.hamcrest.CoreMatchers;
import org.junit.jupiter.api.Test;

@QuarkusTest
@TestProfile(FeaturesResourceTest.class)
public class FeaturesResourceTest implements QuarkusTestProfile { // <1>

    @Override
    public Map<String, String> getConfigOverrides() {
        return Map.of(
            "awesome-feature-enabled", "true"
        );
    }

    @Test
    void test() {
        RestAssured.given()
            .when().get("/features/awesome")
            .then().body(CoreMatchers.is("true"));
    }
}
----
<1> The test class itself can implement `QuarkusTestProfile` if the profile isn't shared across multiple test classes.
This can make the maintenance and reviews of the test code easier.
If multiple test classes depend on the same profile, then that profile will likely need to be declared in a dedicated class.

== Approach #2: mocking the config with Mockito

Now, here's my favorite approach when native testing isn't required.

First, the config properties need to be moved to a dedicated `@ApplicationScoped` bean.
That bean may or may not be used to centralize all config properties from the Quarkus app.

[source, java, title=The config class]
----
import io.quarkus.logging.Log;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.enterprise.event.Startup;
import java.util.Map;
import java.util.TreeMap;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class FeaturesConfig {

    private static final String AWESOME_FEATURE_ENABLED = "awesome-feature-enabled";

    @ConfigProperty(name = AWESOME_FEATURE_ENABLED, defaultValue = "false")
    boolean awesomeFeatureEnabled;

    public boolean isAwesomeFeatureEnabled() {
        return awesomeFeatureEnabled;
    }

    // This is an optional bonus unrelated to the blog post.
    void logConfigAtStartup(@Observes Startup event) { // <1>

        Map<String, Object> config = new TreeMap<>(); // <2>
        config.put(AWESOME_FEATURE_ENABLED, awesomeFeatureEnabled);
        // Omitted: put all config keys and values into the map.

        Log.info("=== Startup configuration ===");
        config.forEach((key, value) -> { // <3>
            Log.infof("%s=%s", key, value);
        });
    }
}
----
<1> This method is executed at application startup. See the https://quarkus.io/guides/lifecycle#listening-for-startup-and-shutdown-events[Application initialization and termination] guide for more details about the lifecycle of Quarkus apps.
<2> `TreeMap` helps automatically sort the map entries by key alphabetically.
<3> This is a nice way to include the application config into the logs.
It can really help identify the root cause of a failure when something goes wrong.
Be careful not to log any sensitive config values (e.g. secrets or passwords) though!

Now that we moved the config to a dedicated class, the code to be tested looks like this:

[source, java, title=The code to be tested]
----
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

@Path("/features")
public class FeaturesResource {

    @Inject
    FeaturesConfig featuresConfig; // <1>

    @GET
    @Path("/awesome")
    public boolean isAwesomeFeatureEnabled() {
        return featuresConfig.isAwesomeFeatureEnabled();
    }
}
----
<1> The configuration is now injected this way.

And here comes approach #2!

[source, java]
----
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import org.hamcrest.CoreMatchers;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@QuarkusTest
class FeaturesResourceTest {

    @InjectMock // <1>
    FeaturesConfig featuresConfig;

    @Test
    void test() {
        Mockito.when(featuresConfig.isAwesomeFeatureEnabled()).thenReturn(true); // <2>
        RestAssured.given()
            .when().get("/features/awesome")
            .then().body(CoreMatchers.is("true"));
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void test2(boolean awesomeFeatureEnabled) {
        Mockito.when(featuresConfig.isAwesomeFeatureEnabled()).thenReturn(awesomeFeatureEnabled); // <2>

        RestAssured.given()
            .when().get("/features/awesome")
            .then().body(CoreMatchers.is("true"));
    }
}
----
<1> The config class is mocked with the `quarkus-junit5-mockito` extension.
<2> This line throws a `NullPointerException` if executed in native mode.




éval :
- dépendance (mockito ou autre)
- compatibilité avec CDI
- config group (l'interface)
- facilité d'implem
- flexbilité
- cout en temps (redémarrage)
- mode natif
- test ordering




















== EN DESSOUS BROUILLON

   préciser dans l'intro : on ne parle pas de %test. dans app.properties mais d'un truc dynamique

   https://quarkus.io/blog/quarkus-component-test/


command line


    @ParameterizedTest
    @ValueSource(booleans = {true, false})



    https://www.diffblue.com/resources/guide-to-overriding-spring-boot-properties-for-testing/


[source, java]
----
import

@ApplicationScoped
public class MyService {

    @ConfigProperty(name = "awesome-feature-enabled", defaultValue = "false")
    boolean awesomeFeatureEnabled;

    // ommitted
}
----






[WARN]
==
NOT ABOUT %test.blabla
==

== Constructor injection

[source, java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class FeaturesService {

    private final boolean awesomeFeatureEnabled;
    private final boolean amazingFeatureEnabled;

    public FeaturesService(
        @ConfigProperty(name = "awesome-feature-enabled", defaultValue = "false") boolean awesomeFeatureEnabled,
        @ConfigProperty(name = "amazing-feature-enabled", defaultValue = "false") boolean amazingFeatureEnabled) {
        this.awesomeFeatureEnabled = awesomeFeatureEnabled;
        this.amazingFeatureEnabled = amazingFeatureEnabled;
    }

    public boolean isAwesomeFeatureEnabled() {
        return awesomeFeatureEnabled;
    }

    public boolean isAmazingFeatureEnabled() {
        return amazingFeatureEnabled;
    }
}
----

[source, java]
----
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@QuarkusTest
class FeaturesServiceTest {

    @Test
    void test() {

        FeaturesService featuresService = new FeaturesService(false, true);

        assertFalse(featuresService.isAwesomeFeatureEnabled());
        assertTrue(featuresService.isAmazingFeatureEnabled());
    }
}
----

== Reflection

https://stackoverflow.com/questions/67318978/injecting-values-into-private-field-in-quarkus-test

mention it as an unriable way?

== System properties

[source, java]
----
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/features")
public class FeaturesResource {

    public static final String AWESOME_FEATURE_ENABLED = "awesome-feature-enabled";

    @ConfigProperty(name = AWESOME_FEATURE_ENABLED, defaultValue = "false")
    boolean awesomeFeatureEnabled;

    @GET
    @Path("/awesome")
    public boolean isAwesomeFeatureEnabled() {
        return awesomeFeatureEnabled;
    }
}
----

[source, java]
----
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static com.gwenneg.blog.config.FeaturesResource.AWESOME_FEATURE_ENABLED;
import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class FeaturesResourceTest {

    @Test
    @Order(1)
    void test1() {

        // This line has no effect on the test outcome when the test is run in native mode.
        System.setProperty(AWESOME_FEATURE_ENABLED, "true");

        given()
                .when().get("/features/awesome")
                .then().body(is("true"));
    }

    @Test
    @Order(2)
    void test2() {

        System.setProperty(AWESOME_FEATURE_ENABLED, "false");

        /*
         * This test depends on a CDI bean with a singleton scope which was already initialized by the previous test.
         * As a consequence, the outcome of this test cannot be changed from the system property.
         */
        given()
                .when().get("/features/awesome")
                .then().body(is("true"));
    }
}
----





== Component test


https://quarkus.io/guides/getting-started-testing#testing-components


[source, java]
----
import jakarta.enterprise.context.ApplicationScoped;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class FeaturesConfig {

    @ConfigProperty(name = "awesome-feature-enabled", defaultValue = "false")
    boolean awesomeFeatureEnabled;

    @ConfigProperty(name = "amazing-feature-enabled", defaultValue = "false")
    boolean amazingFeatureEnabled;

    public boolean isAwesomeFeatureEnabled() {
        return awesomeFeatureEnabled;
    }

    public boolean isAmazingFeatureEnabled() {
        return amazingFeatureEnabled;
    }
}
----

[source, java]
----
import io.quarkus.test.component.QuarkusComponentTest;
import io.quarkus.test.component.TestConfigProperty;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@QuarkusComponentTest
@TestConfigProperty(key = "amazing-feature-enabled", value = "true")
public class FeaturesConfigTest {

    // This line will cause a test failure if run in native mode because @Inject is not supported in tests annotated with @QuarkusIntegrationTest.
    @Inject
    FeaturesConfig featuresConfig;

    @Test
    void test() {

        assertFalse(featuresConfig.isAwesomeFeatureEnabled());
        assertTrue(featuresConfig.isAmazingFeatureEnabled());
    }
}
----

== Config Mapping

https://quarkus.io/guides/config-mappings

[source, java]
----
import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithDefault;

@ConfigMapping(prefix = "features")
public interface FeaturesConfig {

    @WithDefault("false")
    boolean awesomeFeatureEnabled();

    @WithDefault("false")
    boolean amazingFeatureEnabled();
}
----

[source, java]
----
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

@Path("/features")
public class FeaturesResource {

    @Inject
    FeaturesConfig featuresConfig;

    @GET
    @Path("/awesome")
    public boolean isAwesomeFeatureEnabled() {
        return featuresConfig.awesomeFeatureEnabled();
    }

    @GET
    @Path("/amazing")
    public boolean isAmazingFeatureEnabled() {
        return featuresConfig.amazingFeatureEnabled();
    }
}
----

[source, java]
----
import io.quarkus.test.InjectMock;
import io.quarkus.test.Mock;
import io.quarkus.test.junit.QuarkusTest;
import io.smallrye.config.SmallRyeConfig;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.Config;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class FeaturesResourceTest {

    @Inject
    Config config;

    @Produces // Optional
    @ApplicationScoped
    @Mock
    FeaturesConfig featuresConfig() {
        return config.unwrap(SmallRyeConfig.class).getConfigMapping(FeaturesConfig.class); // TODO link alternative way
    }

    @InjectMock
    FeaturesConfig featuresConfig;

    @Test
    void test() {

        // This line throws a NullPointerException if run in native mode.
        Mockito.when(featuresConfig.amazingFeatureEnabled()).thenReturn(true);

        given()
                .when().get("/features/awesome")
                .then().body(is("false"));

        given()
                .when().get("/features/amazing")
                .then().body(is("true"));
    }
}
----


